### ISSUE TITLE
Viewport selection breaks sometimes

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#110]
Haven't figured out the repro steps, but it happens once in a while when you're creating a moderately complex scene like the parthenon.'

**Comment by robertlong** [comment]
@brianpeiris do you think this could be cause by accidentally dragging the viewport rather than clicking? It's pretty easy to mistakenly drag the viewport.

**Comment by brianpeiris** [comment]
Yeah, that could be it. I think I was using a laptop trackpad when I encountered this. We can close it for now maybe.

**Comment by brianpeiris** [comment]
I can't seem repro now, at least not using a mouse on my desktop.

**Comment by robertlong** [comment]
Yeah I couldn't either, but there were a few times where I meant to click but ended up dragging slightly. It definitely confused me. I'm not 100% certain how to fix that though.

**Comment by robertlong** [comment]
Maybe, fire select on mouse up if it is < distance pixels away from the mouse down position?

**Comment by brianpeiris** [comment]
Nah, select on mouse down feels much more responsive. Let's close this and see if it comes back as a pain point.

**Comment by robertlong** [comment]
Ok. Sounds good 👍
