### ISSUE TITLE
Should be able to name a new node immediately

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#117]
We can probably just select the node name input when you create a new node

**Comment by robertlong** [comment]
I think the current UX with naming things based on the imported model, etc. works pretty well. Now that names aren't really important as an identifier, I think we should close this. @brianpeiris what do you think?

**Comment by brianpeiris** [comment]
Yup, makes sense. This was also more important when we were using generic names like "Model 1" during the primary UX. But now the primary UX (through media search and asset upload) gives you good names by default, so that's good.
