### ISSUE TITLE
CLI should create directory path if it doesn't exist and initialize it with the example files

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#120]
You should be able to run `spoke ~/a/path/of/your/choosing/parthenon/`

**Comment by robertlong** [comment]
We should figure out how we want to ignore copying our test files. Maybe we should have another default project folder?

Also maybe we should add this under a `spoke init` command?

**Comment by brianpeiris** [comment]
I dunno, `init` commands feel like a black box to me. We can keep it really simple and explicit -- if the folder you point to doesn't have an ArchitectureKit folder and a Parthenon folder, we copy the examples. If you want to force update, we can add a command/flag to force update them.

**Comment by brianpeiris** [comment]
For the test files, I was thinking we could just ignore that one `test-scenes` folder and put all of our internal things there. Or, yeah just move it out of `example`, either is fine.

**Comment by brianpeiris** [comment]
I'm not arguing that it's uncommon. I'm arguing that it usually means that the CLI is doing something mysterious and special, like setting up your `.git` folder. Whereas we just want to do a simple file copy at the moment.

**Comment by robertlong** [comment]
I think that copying files into a working directory under some conditions without warning is more mysterious.

Perhaps this is a better UX for those new to using cli tools.

1. Run `spoke` in a folder without a `spoke-project.json`
2. Prompt the user: `Creating a new Spoke project. Would you like to add the default assets? y/n`
3. Copy the files if yes.
4. Add the spoke-project.json (empty for now, but we can store project settings in it in the future)

**Comment by brianpeiris** [comment]
Sounds good. Probably not worth us debating the fine points of the CLI anyway, since it's a weird way to ship a GUI tool for artists.

**Comment by robertlong** [comment]
Haha, yeah it definitely is not the best UX for artists.
