### ISSUE TITLE
Object lose their transforms when exporting a combined/static scene

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#140]
See `example/test-scenes/parthenon/parthenon.scene` and the corresponding output in `export-dynamic` and `export-static`

export-static in gltf-viewer.donmccurdy.com:

![2018-08-02 11_38_42-gltf viewer](https://user-images.githubusercontent.com/79419/43603721-aac26848-9648-11e8-9b42-8612e6e90eec.png)

export-dynamic in gltf-viewer.donmccurdy.com:

![2018-08-02 11_40_08-gltf viewer](https://user-images.githubusercontent.com/79419/43603780-d60fdf9e-9648-11e8-95b8-5ed076f7977f.png)

**Comment by robertlong** [comment]
I guess this `applyMatrix()` is incorrect then: https://github.com/MozillaReality/Spoke/blob/master/src/client/editor/SceneLoader.js#L188
