### ISSUE TITLE
Spoke Beta UI Design

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#146]
Here are the design tasks that should be completed for the beta release of Spoke:
- [ ] Inputs
  - [x] Text Field
  - [x] Numeric Field
    - [x] Slider
  - [x] Checkbox
  - [ ] Dropdown
  - [x] File Input
    - [x] Material Input
  - [ ] Color Picker
- [ ] Misc Components
  - [x] Button  
  - [ ] Icon Toggle Button
  - [ ] Icon Dropdown
  - [ ] Tooltip
  - [ ] Scroll bar
  - [x] Context menu
- [ ] Panels
  - [x] Header
  - [x] Container
  - [ ] Drag Handle
  - [ ] Hierarchy Panel
    - [ ] Tree View
    - [x] Context Menus
  - [ ] Asset Explorer Panel
    - [ ] Asset Explorer Panel Toolbar
    - [x] Tree View
    - [ ] Asset Item
    - [x] Context Menus
  - [ ] Properties Panel
    - [ ] Property Group
    - [ ] Node Property Group
    - [x] Input Group
    - [x] Add Component Button
      - [ ] Add Component Dropdown
    - [ ] Context Menus
  - [ ] Viewport Panel
    - [ ] Snapping Menu
    - [ ] Context Menus
- [ ] Toolbar
  - [ ] Dropdown menu
  - [ ] Tool buttons
  - [ ] Save indicator
- [ ] Dialogs
  - [x] Confirm (OK)
  - [x] Prompt (Cancel, OK)
  - [ ] Progress
  - [x] File Dialog
    - [x] Open
    - [x] Save As
- [ ] Modals
  - [x] Save Prefab
  - [ ] Export Modal (This still needs a design @RianLong)

**Comment by RianLong** [comment]
Current roadblocks:

- **Slider:** [Input resets when clicking off slider](https://github.com/MozillaReality/Spoke/issues/154)
- **Dropdown:** [Overset text on dropdown](https://github.com/MozillaReality/Spoke/issues/160)
- **Color Picker:** [Color input appears behind other panels](https://github.com/MozillaReality/Spoke/issues/157)
- **Icon Toggle Button:** Waiting for development to add these to property groups
- **Icon Toggle Dropdown:** Same as above
- **Tooltip:** Waiting on development to add more tooltips and [unable to change the background color](https://user-images.githubusercontent.com/6235018/44122819-673aba3a-9fda-11e8-9d4f-b65b4444b4ba.png)
- **Drag Handle:** Currently appears to be disabled
- **Tree View:** Waiting for development to add unique icons for different elements (node, prefab, etc.)
- **Asset Explorer Panel Toolbar:** In development...
- **Asset Item:** Waiting for development to add FontAwesome icon support for different filetypes
- **Property Group:** Waiting for FontAwesome icon support for different group headers
- **Input Group:** Same as Sliders, they are being affected by the input reset
- **Add Component Button:** Waiting for development to add unique styling (style guide in Figma)
- **Add Component Dropdown:** Same as above
- **Viewport Panel > Context Menus:** Waiting for development to add these to options menus and individual values
- **Snapping Menu:** In development...
- **Context Menus:** Waiting for development to add panel options menus
- **Toolbar:** In development...
- **Dialogs > Progress:** Waiting on development to add a loading bar
