### ISSUE TITLE
File PIcker UX Improvements

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#151]
- [x] Double click should select the file
- [x] Autofocus the filename field in the save dialog(s)
- [x] Directory picker should be more obvious
  > I didn't grok that exporting was prompting me for a folder. The low hanging fruit might be to just auto-fill the export path to -Exported or something. I ended up with three nested "Parthenon" folders -- the root, the project, and then the exported scene :)

Per @gfodor's recommendations: https://github.com/MozillaReality/Spoke/issues/150

**Comment by gfodor** [comment]
nice!
