### ISSUE TITLE
Breadcrumb Bar After Saving

### ISSUE THREAD

**Issue by RianLong** [MozillaReality/Spoke#156]
<img width="640" alt="screen shot 2018-08-13 at 3 28 37 pm" src="https://user-images.githubusercontent.com/6235018/44061769-9b609fc2-9f0e-11e8-931a-052d2cb7b61a.png">
When you save a scene in the "Edit Prefab" view, the breadcrumb bar adds a new button below the ancestor.

<img width="936" alt="screen shot 2018-08-13 at 3 28 50 pm" src="https://user-images.githubusercontent.com/6235018/44061857-e84c9d72-9f0e-11e8-970e-0edfebf0f2b8.png">
This is because the ancestor is being changed to a <div> rather than a button and both are being put in the same parent <div> causing the wrapping to occur.

<img width="638" alt="screen shot 2018-08-13 at 3 27 11 pm" src="https://user-images.githubusercontent.com/6235018/44061898-149b092c-9f0f-11e8-8259-7126ca5c67fa.png">
Here is what the breadcrumb bar should look like.

<img width="906" alt="screen shot 2018-08-13 at 3 27 28 pm" src="https://user-images.githubusercontent.com/6235018/44061915-21d7a8d4-9f0f-11e8-8cfb-4679f15f55ba.png">
With every <button> in a separate <div> allowing them flex in a row without any wrapping.

**Comment by robertlong** [comment]
Closing. We're removing the breadcrumb bar for now.
