### ISSUE TITLE
Hotkeys Affect the Toolbar Selection

### ISSUE THREAD

**Issue by RianLong** [MozillaReality/Spoke#171]
https://giphy.com/gifs/RkLaEV8XTnq9bKEDxe/html5

Using hotkeys currently, do not affect the selection on the toolbar. For example, when tapping `W` to select the move tool, the toolbar does not highlight the move tool button.

Toggles for Global/Local and Snapping should also be able to be controlled by hotkeys and be reflected visually on the toolbar.

**Comment by tony056** [comment]
Have we decided hotkeys for those two toggles?

**Comment by brianpeiris** [comment]
I'm going to call this resolved in #179. Looks like we didn't add a hotkey for toggling global/local but we can add another issue for that if we feel we need it.
