### ISSUE TITLE
Toolbar Menu Dropdown Placement Off

### ISSUE THREAD

**Issue by RianLong** [MozillaReality/Spoke#173]
https://giphy.com/gifs/RkG1y1ge4RAMhjohrm/html5

The dropdown menu in the toolbar is currently using the Context Menu library and is rendered wherever the user clicks. This causes the dropdown to appear in different places based on where you click the button.

The dropdown should be flush left at all time as shown below:
<img width="864" alt="screen shot 2018-08-20 at 2 59 53 pm" src="https://user-images.githubusercontent.com/6235018/44369020-b8a38880-a489-11e8-9912-056cfa7198f3.png">

**Comment by brianpeiris** [comment]
Looks like this was fixed in #179
