### ISSUE TITLE
Clicking on objects in viewport throws an error.

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#183]
1. Start fresh
1. Drop a door into the view
1. Try to click on the door.
1. Error in console:
---
	TypeError: object.updateMatrixWorld is not a function three.module.js:5033
		expandByObject
		three.module.js:5033
		setFromObject
		three.module.js:4890
		Viewport/<
		Viewport.js:268:8
		execute
		signals.js:93
		dispatch
		signals.js:384:23
		Signal/this.dispatch
		signals.js:187
		select
		Editor.js:1516:4
		handleClick
		Viewport.js:138:8
		onMouseUp
		Viewport.js:146:6

**Comment by robertlong** [comment]
Fixed in https://github.com/MozillaReality/Spoke/commit/5d4212e723a0c914f4baa575f15938dfcf75fb9a
