### ISSUE TITLE
Edit tool keybinds don't work unless viewport is focused

### ISSUE THREAD

**Issue by mquander** [MozillaReality/Spoke#188]
If anything but the viewport is focused (e.g. the scene hierarchy) and "W", "E", etc. is pressed to switch editor tools, the switch doesn't happen and there is no UI feedback. This sounds minor and arguable, but I think it is pretty bad and it will make people feel that those keys are just mysteriously unreliable and broken.

**Comment by robertlong** [comment]
Fixed in e21395ef54969efeda5435d9cdac473185a306c0
