### ISSUE TITLE
Undo stack appears broken

### ISSUE THREAD

**Issue by mquander** [MozillaReality/Spoke#189]
Example:

1. Open an empty scene.
2. Create a prefab from a GLTF model.
3. Use the viewport translation tool to move the model one unit in one direction, and release the mouse.
4. Use the viewport translation tool to move the model one unit in another direction, and release the mouse.
5. Ctrl-Z. Step 4 will be correctly undone.
6. Ctrl-Z. Nothing will happen.
7. Ctrl-Z. Nothing will happen.
8. Ctrl-Z. Step 3 will be undone.
9. Ctrl-Shift-Z. Step 3 will be redone.
10. No further amount of redoing will redo step 4.

**Comment by gfodor** [comment]
Another case:

- Add a node
- Ctrl-Z doesn't remove it (afaict)

**Comment by brianpeiris** [comment]
I couldn't repro @mquander's original scenario, presumably because we removed all the prefab code. 
Fixed undo/redo for transform changes (e.g. when you scrub the transform values in the properties panel) and fixed undo/redo when you add an object/model.
