### ISSUE TITLE
No vertical scrollbar in scene hierarchy in Firefox

### ISSUE THREAD

**Issue by mquander** [MozillaReality/Spoke#190]
It doesn't seem like a vertical scrollbar ever appears in the scene hierarchy in Firefox. If you add more nodes than can fit, the hierarchy panel will cut off at the bottom and there will be no way to scroll it.

A scrollbar correctly appears in Chrome.

**Comment by robertlong** [comment]
Fixed in a03aec462fed324d2faa18aa727fc43add9fab76
