### ISSUE TITLE
Scene node UI in funny state after creating prefab

### ISSUE THREAD

**Issue by mquander** [MozillaReality/Spoke#191]
1. Open an empty scene.
2. Drag a GLTF file into the viewport, creating a prefab.
3. The node in the scene hierarchy associated with your prefab will be visually highlighted.
4. However, it secretly isn't focused somehow, because if you press Backspace, Delete, or Ctrl-D, none of them will work. You have to click it before those will work.

**Comment by robertlong** [comment]
Fixed in e21395ef54969efeda5435d9cdac473185a306c0
