### ISSUE TITLE
Add nav-mesh component

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#197]
The `nav-mesh` component can be added to a node with a `gltf-model` component. It will traverse it's children and look for the first `Three.Mesh` object to use as a nav-mesh.

To Do
- [x] Update Hubs to the most recent version of aframe-extras with the [nav-mesh generation speedup](https://github.com/donmccurdy/aframe-extras/pull/237#discussion_r187217171)
- [x] Ensure existing scenes with the pre-computed nav-mesh data structures do not break.
- [ ] Add the `nav-mesh` component to Spoke. It doesn't need any props.

Existing environments will eventually need to be updated to remove the pre-computed nav-mesh data structure. We won't be using that data any more and there's no use generating it in `mr-social-assets`.

Once that is done. The custom gltf component inflator can be removed: https://github.com/mozilla/hubs/blob/master/src/gltf-component-mappings.js#L32

**Comment by brianpeiris** [comment]
I think this is done barring any bugs we find when the full Spoke-to-Hubs flow is complete.
