### ISSUE TITLE
Skybox can be selected, is confusing

### ISSUE THREAD

**Issue by mquander** [MozillaReality/Spoke#202]
If you add a skybox to a node, you can then click in some areas on the viewport to select the skybox (clicking near the "sun" of the default skybox works for me.) At that point, you see a big bounding box, a meaningless properties window on the right, and you can't select anything else in the viewport.

Robert made it sound like the desired behavior is that skyboxes can't be selected in the viewport, which makes sense to me.

**Comment by robertlong** [comment]
Fixed in e19409f4401c2afb3780ede2e30f980a88973d36

**Comment by robertlong** [comment]
Note that it still shows the bounding box. I think that's fine for now.
