### ISSUE TITLE
Generate nav mesh automatically on publish

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#222]

**Comment by gfodor** [comment]
as part of this can also remove the menu item to generate it (under File)

**Comment by brianpeiris** [comment]
Left the menu item in for now, since it may be useful if we want to debug things or experiment with generating nav meshes on demand while editing a scene.
But the implementation in https://github.com/MozillaReality/Spoke/commit/b8844fd7f962a7fc2d2636c85130e88d27d21949 will discard any current nav mesh in the scene and regenerate it on publish.
Also left the nav mesh visible in the scene graph, mainly for debugging -- it's easier to toggle the mesh visibility to inspect it that way.
