### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/Spoke#248]
Which will include a beaver

**Comment by robertlong** [comment]
Can we use the logo that @RianLong made for Spoke and make the beaver our mascot?

Rust does something similar.


![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/2000px-Rust_programming_language_black_logo.svg.png)


![](https://community.rs/resources/rustacean.png)

**Comment by robertlong** [comment]
Also I recommend the positioning of the logo should be in the toolbar to the left of the hamburger menu. It can eventually serve as the link to get back to the homepage in the hosted version.

**Comment by gfodor** [comment]
yeah we can incorporate the sphere element if you think that makes sense. i was on the fence about it since it felt like a more "professional tool" vibe -- perhaps we can make a more light-hearted variant of it. putting it to the left of the hamburger menu seems weird tho, isn't the hamburger menu in apps always in the corner? any examples of this? we could put it to the right (or put it center where the name is now)

**Comment by gfodor** [comment]
oh and i agree w/ beaver mascot :) i was looking for a good beaver model but i think we'll have to make one -- it can be the default model if you don't enter a URL, like the duck in hubs

**Comment by gfodor** [comment]
no beaver mascot, but logo's added to homepage + spoke app
