### ISSUE TITLE
Show current scene complexity

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/Spoke#249]
The UI should show the user in some form how expensive their scene is overall, and ideally also give some metrics about the current viewport camera's draw calls etc.

**Comment by brianpeiris** [comment]
Can we call this closed with #318?

**Comment by robertlong** [comment]
The renderer stats aren't currently accurate. They are excluding the helper scene, but there are items such as the spawn point and some helpers that are being counted.

**Comment by robertlong** [comment]
Going to merge this with #549
