### ISSUE TITLE
Add More Components

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#25]
- [x] spawn-point
- [x] skybox (fix scale)
- [x] hoverable
- [x] spot-light
- [x] scene-shadow
- [x] super-spawner (depends on hoverable)
- [ ] sticky-zone
- [ ] hide-when-quality
- [x] visible
- [x] nav-mesh (depends on visible)
- [ ] collision-filter
- [ ] body
- [ ] shape
- [x] ~css-class~ replaced with interactable which is inflated as `setAttribute("css-class", "interactable")` in Hubs.
- [ ] sound
- [ ] layers
- [ ] text
- [x] loop-animation
- [ ] billboard
- [ ] water
- [ ] fog (only on scene)
- [x] media-loader

**Comment by robertlong** [comment]
Closing this issue because we removed components from Spoke.
