### ISSUE TITLE
Cannot click-drag inside numerical parameter inputs to selectively change digits

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/Spoke#269]
It's common practice to highlight part of a parameter (for example, click-dragging over the first decimal place) to then type over that value. The current design does not allow this and causes a user to accidentally change their value(s). Consider making the virtual slider design use the parameter label as a click-drag spot.

**Comment by netpro2k** [comment]
The scrollwheel should also not change values as its very easy to change things by mistake while just scrolling through the property inspector.

**Comment by robertlong** [comment]
I'm going to move this to #67 since I think that will fix this. I think disabling the scroll wheel behavior is a good idea as well.
