### ISSUE TITLE
Initial Styling

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#28]
- [x] Panel headers should be differentiated from their content (dd1ef2e)
- [x] Styled checkbox component
- [x] Input group alignment (42eb7eef)
- [x] Scene hierarchy label vertical alignment (dd1ef2e)
- [x] Close button styling (button removed in #73)
- [x] Property group header should have greater font weight 
- [x] Property group header should have a greater border-top/bottom

**Comment by brianpeiris** [comment]
Fixed most of these anyway. I'm not going to tackle the checkbox now. And I'm personally undecided on whether a bigger font weight is better.

**Comment by brianpeiris** [comment]
Current (new) UI design has resolved this! 🎉
