### ISSUE TITLE
Spotlights are offset in Hubs from how they appear in Spoke

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/Spoke#298]
Could be related to [this bug]( https://github.com/MozillaReality/Spoke/issues/297), but there is a discrepancy between how lights appear in Spoke and how they appear in Hubs.

![spotlight_spoke](https://user-images.githubusercontent.com/31968496/46440087-34465580-c717-11e8-97e1-8832deefbb26.png)
![spotlight_hubs](https://user-images.githubusercontent.com/31968496/46440092-36101900-c717-11e8-8c71-3292f48b47c4.png)

**Comment by j-conrad** [comment]
Note:  Did not test with other light types

**Comment by gfodor** [comment]
seems like a bug we should fix before beta
