### ISSUE TITLE
checkboxes for remixing and promotion don't look checked.

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#301]
Can you tell that the checkboxes in this image are actually checked? I couldn't until I tried to check them, realizing they were already checked. It should have an actual white dot or x or checkmark inside of the box.

<img width="1138" alt="firefox nightlyscreensnapz049" src="https://user-images.githubusercontent.com/276938/46444511-2a2c5300-c727-11e8-9436-ebfc171d7aaf.png">

**Comment by gfodor** [comment]
these prompts are under legal review and so when I go through and refine this flow based on that I'll modify these

**Comment by joshmarinacci** [comment]
The issue isn't really the prompts. It's the checkbox control itself.

**Comment by brianpeiris** [comment]
Also just realized that the checkboxes are on the far right of their labels, which very unorthodox.
