### ISSUE TITLE
nav-path generation shouldn't be tried on all objects

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#302]
I created a scene with just one object, a snowman from here:

https://sketchfab.com/models/65649513903f49dfaf00eaf843186780

The scene published fine, but as soon as I tried to move it jumped me to be on top of the snowman's arm and stuck me there.

I *think* it tried to turn the snowman's arm into a navpath and is restricting me to there.

<img width="1958" alt="firefox nightlyscreensnapz050" src="https://user-images.githubusercontent.com/276938/46444610-9444f800-c727-11e8-864f-60614f8fdb95.png">

**Comment by gfodor** [comment]
i think this use-case is important enough we should fix it before beta. added to beta
