### ISSUE TITLE
there should be a way to reset a model

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#306]
Right now I can rescale a model with the scale tool. There is no way to get it back to 1.0 scaling, and fix any aspect ratio issues. I should be able to right click on it for a menu in the Heirarchy view or there should be a 'reset' button next to the scale in the properties sheet. Probably the same for translate and rotation too.

**Comment by gfodor** [comment]
Sorry, whats the difference between this reset button and entering 1/1/1 in the transform? Is this just a convenience to do that? (eg like Alt-G/R/S in blender?)

**Comment by joshmarinacci** [comment]
yes, just a convenience.

**Comment by robertlong** [comment]
I'm going to merge all resetting of properties into #514
