### ISSUE TITLE
re-running .exe causes silent failure (if server is not shut down first)

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/Spoke#311]
Not sure how hard this is, but since the server keeps running when I close the spoke window, if I re-launch the exe it just silently fails unless I knew to close the server window.

Two things that would help:

- If I run the exe and the server is already running, open a new browser window.

- When the server is running, keep track of how many browser tabs are currently connected. When it drops to zero (likely after some short grace period) shut the server down.

**Comment by mquander** [comment]
This all would be nice, I'm not going to get to it by tomorrow though so someone else should do if it needs doing.

**Comment by brianpeiris** [comment]
The root cause of the silent failure was because the server terminated when the default port was in use. I fixed that issue. I think that's sufficient for v1. If we want to detect multiple processes or detect closed browser tabs, I'll leave that for a new ticket.
