### ISSUE TITLE
Imported models are cached, preventing updates to models

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/Spoke#316]
While attempting to make changes to Sketchfab models (reuploading to Sketchfab, changing material settings on Sketchfab site, etc.), the URL does not change after updating. This causes me to not be able to see those updated models when I reimport them into Spoke since we are currently caching any and all imported models. 
I had to delete cache files and refresh the Spoke tab in order to see those updated models on import.
This is likely to confuse people who are making their own models and iterating them.

Consider adding a 'Re-import' button to an existing imported model or some other way to bust the cache.

**Comment by brianpeiris** [comment]
Gonna un-assign, since I'm not actually working on it at the moment.

**Comment by gfodor** [comment]
I agree this is busted, but think we should prioritize post-beta
