### ISSUE TITLE
Navmesh is being overridden after clicking 'Publish to Hubs'

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/Spoke#317]
1. Imported a model
2. Generated navmesh on it using File menu
3. Imported another model (that I don't want navmesh on)
4. Clicked 'Publish to Hubs'

Result:  Original FloorPlan object seemingly gets nuked and a new navmesh gets generated on the unwanted model (imported on step 3 above). First model has no navmesh anymore.

**Comment by gfodor** [comment]
I think this bug can/will be addressed when we do our iteration on nav mesh generation controls -- in particular this seems to imply having a way to mask in/out certain meshes for the generation is important.

The UX I'm imagining right now is:
- The nav mesh component has a checkbox (on by default) for "auto-generate" -- when checked, the semantics for nav mesh generation are basically what they are now.

- When unchecked, we no longer generate nav meshes automatically -- it requires a manual generation step. The controls for this are then enabled as well in the component, such as the recast knobs and the ability to exclude meshes.

**Comment by mquander** [comment]
I like this UX except I still think that if a navmesh isn't created, then autogenerating a navmesh in Spoke is probably inferior to autogenerating it in Hubs.

**Comment by robertlong** [comment]
@mquander The navmesh can take a minute or more to generate on a large environment. It also still has the problem of spawning at the origin when there is no spawn point and the lack of a fly mode. It could be ok to do that on smaller scenes with a decent spawn point at the origin.

**Comment by mquander** [comment]
I see, if it takes that long on realistic environments and it's not for some easy-to-fix reason then I admit defeat and we should indeed do it in Spoke. In that case all I suggest is that you make sure to set a flag on the exported scene that lets us detect that the nav mesh is autogenerated -- else we will be hosed someday when we are unable to distinguish between crappy autogenerated ones and manually tweaked ones that someone actually cares about.

**Comment by robertlong** [comment]
This is now in Spoke
