### ISSUE TITLE
weird naming issue

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/Spoke#389]
I imported a model and named it 'cake'. If I leave the cursor in the name field and press the enter key repeatedly, the name of the model in the hierarchy view adds a constantly incrementing number.

<img width="485" alt="firefox nightlyscreensnapz102" src="https://user-images.githubusercontent.com/276938/49038046-a9129a80-f170-11e8-85f0-b79ee0f256f1.png">

**Comment by joshmarinacci** [comment]
https://sketchfab.com/models/69f2fedbd949459cbf8993305b439df8

**Comment by robertlong** [comment]
No, I think there's a bug in how the name de-duplication works. I want to move away from a name based system pretty soon anyway. I'll pick this up then. Hopefully it's not causing too many issues?

**Comment by joshmarinacci** [comment]
It wasn't a big issue. Just weird. I'm using the name set in Spoke to attach an event handler on the code side. so I just named it cake2.
