### ISSUE TITLE
Stuck verifying email

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#393]
From a support email:

> Hello, I’m using the Spoke tool on Windows to create a scene (Version 0.6.2 Beta). Part of the process to upload the scene is to verify my email and I end up here: 
> ![image](https://user-images.githubusercontent.com/79419/49593343-56d83300-f941-11e8-94a6-3d1a4c3a6d52.png)
>  I haven’t yet received the email, I may have typed it incorrectly, however I am now stuck waiting with no option to cancel or re-type my email address without refreshing the page.
> It would be great if it at least showed you the email address you should be checking. Better still would be having an option to cancel or go back.

IIRC, we intentionally decided not to allow users to cancel out of this dialog, since we were worried users would do it unintentionally before reading the prompt. 

Showing the email address sounds like a good suggestion though.

**Comment by robertlong** [comment]
I kinda think we should add the ability to cancel in this dialog. I've entered the wrong email address on this page before and it prevented me from closing the dialog. What happens if you enter the wring email and you haven't saved your work 😧  @gfodor @brianpeiris

**Comment by gfodor** [comment]
cancel seems fine, as long as it's very understated. main concern would be that users would click it without reading thinking it's a close/OK button. i'd make it a dark grey link in the lower left "Don't want to log in yet?" or something.

**Comment by robertlong** [comment]
Yeah, I think a grey link similar to the tutorial UI will work.
