### ISSUE TITLE
Adding collision box(es) breaks all lighting

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/Spoke#415]
If you have a Spoke scene with lights, adding a collision box (or multiple boxes) makes all the lights move to the origin, face the default orientation, and sets their color to white when you click 'Create a Room with this Scene' after publishing to Hubs.

Repro:    
1. Start with default Spoke scene.
2. Add a few spotlights pointing down at the ground and move them to a few different places.
3. Add a collision box.
4. Save / Publish to Hubs.
5. Create a room with the scene and notice the lights are all moved.

**Comment by robertlong** [comment]
Fixed in https://github.com/mozilla/hubs/pull/836
