### ISSUE TITLE
Got stuck dragging the camera around when trying to move objects

### ISSUE THREAD

**Issue by johnshaughnessy** [MozillaReality/Spoke#507]
Not sure how to repro this yet.

**Comment by robertlong** [comment]
@misslivirose found it as well and I captured the state of the SpokeControls and the InputManager:

![bugreport1](https://user-images.githubusercontent.com/1753624/56770356-98d70980-6768-11e9-9073-0a27438ea304.png)
![bugreport2](https://user-images.githubusercontent.com/1753624/56770355-98d70980-6768-11e9-9d51-1cf5d99a5ede.png)

**Comment by misslivirose** [comment]
I think that this is the same as #531 - I'm reproing consistently after leaving the atb

**Comment by robertlong** [comment]
Duplicate of #531
