### ISSUE TITLE
Publishing fails when scene contains an uploaded video

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#521]

**Comment by johnshaughnessy** [comment]
![image](https://user-images.githubusercontent.com/4072106/56768158-6aeec680-6762-11e9-8fda-137ec3123cca.png)

**Comment by brianpeiris** [comment]
This also happens with GIFs from the search results.

**Comment by robertlong** [comment]
It looks like this happens for all videos.

**Comment by robertlong** [comment]
Closing in favor of #556
