### ISSUE TITLE
Warning display for components that are attached to missing/renamed nodes

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#53]
Should we inform the user that their `.scene` file contains components that are supposed to be attached to nodes that are now missing or renamed?
If not, should we still save those components in the `.scene` file?

**Comment by tony056** [comment]
Maybe we should make the missing node clickable but not editable, so users can see components attached to it. However, users are not allowed to update those components until they solve the missing node issues. 
If we enable #54 before this, then I think the missing node can be disappeared after the user moves all its children nodes to other alive nodes.

**Comment by brianpeiris** [comment]
I think that makes sense for nodes attached to missing nodes, but this issues is about components attached to missing nodes.

**Comment by tony056** [comment]
Components are supposed to attach to existing nodes, so I think it's fine to ignore components attached to missing nodes while loading the file and remove them while saving the file. I think we can start with that to see whether it's a common issue that users always face with. If so, then we can figure out how to inform users and keep information in the `.scene` file later.
