### ISSUE TITLE
Alt-tabbing away and back to Spoke causes scene manipulation to stop working

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#531]

**Comment by robertlong** [comment]
@brianpeiris I'm not able to reproduce this one. Could you provide a little more info? I'm testing on Mac, maybe it's Windows specific?

**Comment by brianpeiris** [comment]
I can reproduce consistent in the current version of spoke-dev. 

Steps to reproduce are pretty simple:
1. Start a new project
2. Alt-tab to a different window
3. Alt-tab back to spoke
4. Click on the spawn point in the viewport. It does not get selected, instead the left mouse button actually orbits the scene. You can still fly around with the right mouse button.

I can repro in both Firefox and Chrome on Windows.

**Comment by brianpeiris** [comment]
Oh, actually you don't even have to alt-tab away. The Alt button immediately switches to this orbit mode and you can't switch back.
