### ISSUE TITLE
Images don't resolve in scene preview after publish

### ISSUE THREAD

**Issue by misslivirose** [MozillaReality/Spoke#533]
If you have an image as a skybox, the scene preview screen (after publishing and viewing) is very vivid because you end up inside the 'loading' cube:

![image](https://user-images.githubusercontent.com/4313320/56769031-e0f42d00-6764-11e9-93a3-51d7f5f3c5b5.png)

**Comment by robertlong** [comment]
I think this belongs in the Hubs repo. I've posted it there and I'm going to close this issue.
