### ISSUE TITLE
Scene manipulation breaks if you try to duplicate a video with 'ctrl+d'

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#534]

**Comment by robertlong** [comment]
Merging with #521

**Comment by brianpeiris** [comment]
Hmm, #521 doesn't seem related. Did you mean to merge into different issue?

**Comment by robertlong** [comment]
Oops, yeah I meant https://github.com/MozillaReality/Spoke/issues/556 video nodes have a bug with cloning.
