### ISSUE TITLE
Infinite scrolling breaks when you reach the end of the results

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#557]
This is probably due to the result deduplication. Probably stop deduplicating and correct the `loadMore` condition.

**Comment by netpro2k** [comment]
This is particularly bad since we end up repeatedly requesting the next page as quickly as we can, slamming our servers.

**Comment by robertlong** [comment]
I can no longer reproduce this bug and the code does look right. We can re-open this if we see it happening again.

**Comment by robertlong** [comment]
After some discussion, I think this commit should fix things in the event that a search result returns an error: https://github.com/MozillaReality/Spoke/commit/0c063e86b8751245d54429f0ecd733e040429be4
