### ISSUE TITLE
Static Property Functionality and Saving

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#85]
The static property is currently not serialized on save and is somewhat hard to use as is.

- The static property is not a component so it will need to be added as another top level property in the scene format's entity object to serialize the property. Should it be a component instead to simplify the implementation?
- Nodes with a scene reference component should likely have all of their children set as static. Should static have two modes: one that applies to just the node it's on and another that applies to all of it's children. If this second mode is added what would happen when setting static to false on one of the child nodes?
- Should objects dragged into the scene be set to static by default?
- Should all nodes whether created or loaded from a glTF be static by default?

**Comment by brianpeiris** [comment]
I think all these questions were resolved in #121, right?
