### ISSUE TITLE
Duplicate naming conflicts

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/Spoke#94]

**Comment by brianpeiris** [comment]
I know there was a bigger discussion around this, but I patched the critical bug that was blocking the tutorial in https://github.com/MozillaReality/Spoke/commit/a37b0b6ac30275d8061feaf257501528013d7062

**Comment by tony056** [comment]
Several cases:
- Cases where we check for duplicate names but do not modify them:
1. On renaming a node in hierarchy panel or property panel `editor.isUniqueNodeName(name)`

- Cases where we de-duplicate names automatically:
1. On adding a new node / duplicating a node `editor.addObject()`
2. On adding / changing a scene ref `editor._loadSceneReference()`

- Cases where we de-duplicate names based on a user action:
1. On importing a glTF file (Still not sure how this would work, but we would show a dialog with any conflicts on import and you could correct them there or cancel if you don’t want to modify the file)

- reset that node list when loading or popping scenes.
